import { useEffect, useMemo, useState } from "react";
import { EmptyState } from "../../../design-system";
import PumpWorkspaceCommandPalette from "../components/PumpWorkspaceCommandPalette";
import PumpWorkspaceComingSoon from "../components/PumpWorkspaceComingSoon";
import PumpWorkspaceDrawer from "../components/PumpWorkspaceDrawer";
import PumpWorkspaceTimeline from "../components/PumpWorkspaceTimeline";
import { IconAlert, IconBox, IconHistory, IconSearch, IconWrench } from "../components/PumpWorkspaceIcons";
import { getCMReports } from "../../../api/ai5rClient";
import { mapCMReportRecord, withResolvedArea } from "../utils/cmMapping";
import WorkspaceShell from "../workspace/WorkspaceShell";
import { useWorkspaceTheme } from "../workspace/WorkspaceTheme";
import { useWorkspaceShortcuts } from "../workspace/WorkspaceShortcuts";
import { useWorkspaceDrawer } from "../workspace/WorkspaceDrawer";
import { useWorkspaceNavigation } from "../workspace/WorkspaceNavigation";
import { WORKSPACE_KEYS } from "../workspace/WorkspaceRegistry";
import "./MaintenanceHistory.css";

const unavailable=(label)=><PumpWorkspaceComingSoon label={label}/>;
export default function FailureAnalysisWorkspace({navContext}){
 const [reports,setReports]=useState([]),[loading,setLoading]=useState(true),[selected,setSelected]=useState(navContext?.selectId??null);const [theme,setTheme]=useWorkspaceTheme();const [paletteOpen,setPaletteOpen]=useWorkspaceShortcuts();const {drawer,openDrawer,closeDrawer}=useWorkspaceDrawer();const navigate=useWorkspaceNavigation();
 useEffect(()=>{let active=true;getCMReports().then(items=>Promise.all(items.map(mapCMReportRecord).map(withResolvedArea))).then(items=>{if(active){setReports(items);if(!selected&&items.length===1)setSelected(items[0].id)}}).catch(()=>{if(active)setReports([])}).finally(()=>active&&setLoading(false));return()=>{active=false}},[]);
 const report=reports.find(item=>item.id===selected)??null;const timeline=useMemo(()=>report?[{id:report.id,tier:"attention",tag:"Failure",title:report.failureDescription||"Failure report",date:report.id}]:[],[report]);const actions=useMemo(()=>[{id:"timeline",label:"View failure timeline",hint:"History",icon:IconHistory,run:()=>document.getElementById("timeline-section")?.scrollIntoView({behavior:"smooth"})},{id:"evidence",label:"View evidence",hint:"Unavailable",icon:IconBox,run:()=>openDrawer("Evidence")},{id:"recommendation",label:"View recommendation",hint:"Unavailable",icon:IconWrench,run:()=>openDrawer("Recommendation")}],[openDrawer]);
 if(loading)return <WorkspaceShell theme={theme}><div className="workspace-empty">Loading failure analysis...</div></WorkspaceShell>;
 if(!report)return <WorkspaceShell theme={theme}><EmptyState title="No failure analysis selected" description="Open a Corrective Maintenance report to view its failure analysis."/></WorkspaceShell>;
 return <WorkspaceShell theme={theme}><header className="chrome-bar"><div className="chrome-inner"><div className="crumb"><button className="btn-link" onClick={()=>navigate(WORKSPACE_KEYS.PUMP,{assetTag:report.equipmentTag})}>Pump</button><span className="sep">/</span><span>Failure Analysis</span><span className="sep">/</span><b>{report.id}</b></div><div className="chrome-right"><button className="cmdk-trigger" onClick={()=>setPaletteOpen(true)}><IconSearch width="14" height="14"/> Actions <kbd>Ctrl K</kbd></button><button className="icon-btn" onClick={()=>setTheme(theme==="light"?"dark":"light")}>Theme</button></div></div></header><div className="workspace-shell"><section className="identity"><span className="eyebrow">Failure analysis</span><h1>{report.equipmentTag}</h1><p>{report.area??"Area unavailable"} - {report.failureCategory??"Failure category unavailable"}</p></section><div className="workspace-grid"><main className="main-column"><section className="assessment-section"><div className="section-head"><div><span className="eyebrow">Failure summary</span><h2>{report.failureDescription??"Unavailable"}</h2></div><span className="status-signal attention">{report.severity??"Severity unavailable"}</span></div><div className="info-row"><span className="k">Immediate action</span><span className="v">{report.immediateAction??"Unavailable"}</span></div><div className="info-row"><span className="k">Corrective action</span><span className="v">{report.correctiveAction??"Unavailable"}</span></div><div className="info-row"><span className="k">Downtime</span><span className="v">{report.downtimeHours??"Unavailable"}</span></div></section><section className="assessment-section"><PumpWorkspaceTimeline items={timeline}/></section>{["Evidence Strip","Observation","Investigation","Root Cause","Verification","Attachments","Recommendation","Approval","Sign-Off"].map(label=><section className="assessment-section" key={label}><div className="section-head"><h2>{label}</h2></div>{unavailable(label)}</section>)}</main><aside className="inspector-rail">{["Replacement Parts","Seal Information","Related PM","Related Condition Monitoring"].map(label=><section className="rail-section" key={label}><h3>{label}</h3>{unavailable(label)}</section>)}</aside></div></div><div className="action-bar"><div className="action-bar-inner"><div className="action-bar-status"><span className="label">Failure analysis is read-only</span><span className="meta">Approval and sign-off are unavailable.</span></div></div></div><PumpWorkspaceCommandPalette open={paletteOpen} onClose={()=>setPaletteOpen(false)} actions={actions} pumpTag={report.equipmentTag}/><PumpWorkspaceDrawer open={Boolean(drawer)} onClose={closeDrawer} title={drawer??"Unavailable"}>{unavailable(drawer??"This capability")}</PumpWorkspaceDrawer></WorkspaceShell>;
}