from FACTORY.ARTIFACTS import TemplateLoader


def test_load_main_template():
    loader = TemplateLoader()

    text = loader.load(
        "FASTAPI",
        "main.py.tpl",
    )

    assert "FastAPI" in text
    assert "{{project_name}}" in text


def test_load_readme_template():
    loader = TemplateLoader()

    text = loader.load(
        "FASTAPI",
        "README.md.tpl",
    )

    assert "Generated by AI5R" in text


def test_load_requirements_template():
    loader = TemplateLoader()

    text = loader.load(
        "FASTAPI",
        "requirements.txt.tpl",
    )

    assert "fastapi" in text
