from dataclasses import dataclass, field
from typing import List


@dataclass
class FoundationManifest:
    """
    AI5R Foundation Manifest

    Describes a foundation product that can be generated by AI5R Factory.
    """

    foundation: str
    code: str
    version: str = "1.0"
    components: List[str] = field(default_factory=lambda: [
        "object",
        "registry",
        "validation",
        "runtime",
        "manifest",
        "station",
        "specification",
        "freeze",
    ])
    tests: bool = True
    docs: bool = True

    def normalized_name(self):
        return self.foundation.strip().upper()

    def package_name(self):
        return self.foundation.strip().upper()

    def module_prefix(self):
        return self.foundation.strip().lower()

    def to_dict(self):
        return {
            "foundation": self.foundation,
            "code": self.code,
            "version": self.version,
            "components": self.components,
            "tests": self.tests,
            "docs": self.docs,
        }
