class {{ class_name }}:
    """
    Enterprise Object generated by AI5R Foundation Generator.
    """

    def __init__(self, object_id: str, name: str):
        self.object_id = object_id
        self.name = name

    def to_dict(self) -> dict:
        return {
            "object_id": self.object_id,
            "name": self.name,
        }
